# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=200)),
                ('usage_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='img',
            name='search_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrez.SearchQuery'),
        ),
    ]
