# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='img',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
