# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0002_auto_20170530_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartrez.SearchQuery')),
            ],
        ),
        migrations.RenameField(
            model_name='img',
            old_name='img_path',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='img',
            name='height',
        ),
        migrations.RemoveField(
            model_name='img',
            name='usage_times',
        ),
        migrations.RemoveField(
            model_name='img',
            name='width',
        ),
    ]
