# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0003_auto_20170531_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='thumb_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
