# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0004_img_thumb_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected_imgs',
            name='search_query',
        ),
        migrations.DeleteModel(
            name='Selected_imgs',
        ),
    ]
