# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0005_auto_20170602_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
