# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrez', '0006_img_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_id',
            field=models.IntegerField(default=0),
        ),
    ]
